
import BD.Documentos;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author edgar
 */
public class VistaDocStatus extends javax.swing.JInternalFrame {
 Documentos doc;
 DefaultTableModel modeloDoc;
    /**
     * Creates new form VistaDocStatus
     */
    public VistaDocStatus() {
        initComponents();
         doc=new Documentos();
         RadioGroup();
          tablanew();
           modeloDoc = (DefaultTableModel) tablaArchivo.getModel();
           TotalDocumentos();
           TablaDimensiones2();
    }
  private void tablanew(){
          DefaultTableModel modelo3=new DefaultTableModel(){
    public Class getColumnClass(int indiceColumna){
        Object stefany=getValueAt(0, indiceColumna);
        if(stefany == null){
            return Object.class;
        }else{
        return stefany.getClass();
        }
       }
        };
         
        modelo3.addColumn("No. Empleado",new Object[] {});
        modelo3.addColumn("Imagen",new Object[] {});
        modelo3.addColumn("Nombre",new Object[] {});
        modelo3.addColumn("Acta de Nac.",new Object[] {});
        modelo3.addColumn("Carta Ant. Pen.",new Object[] {});
        modelo3.addColumn("Comp. Domicilio",new Object[] {});
        modelo3.addColumn("Certi.  Estudios",new Object[] {});
        modelo3.addColumn("Contrato",new Object[] {});
        modelo3.addColumn("Curp",new Object[] {});
        modelo3.addColumn("CV",new Object[] {});
        modelo3.addColumn("INE",new Object[] {});
       
        this.tablaArchivo.setModel(modelo3);
      
      }
      private void limpiar(JTable tabla) {
        while (tabla.getRowCount() > 0) {
            ((DefaultTableModel) tabla.getModel()).removeRow(0);
        }
    }
      private void TotalDocumentos(){
        limpiar(tablaArchivo);
        
        doc.ReadDocumentos(modeloDoc);
    
    }
           private void TablaDimensiones2(){
    
      tablaArchivo.setRowHeight(50);
      tablaArchivo.getColumnModel().getColumn(2).setPreferredWidth(300);
      /*tablaEmpleado.getTableHeader().setFont(new Font("Ubuntu", 1,15));
      tablaEmpleado.getColumnModel().getColumn(6).setPreferredWidth(2);
      tablaEmpleado.getColumnModel().getColumn(0).setPreferredWidth(40);
      tablaEmpleado.getColumnModel().getColumn(1).setPreferredWidth(10);
      tablaEmpleado.getColumnModel().getColumn(2).setPreferredWidth(250);
       tablaEmpleado.getColumnModel().getColumn(4).setPreferredWidth(50);
      /*
      tablaProductos.getTableHeader().setFont(new Font("Ubuntu", 1,15));*/
    }
           private void RadioGroup(){
       radioGroup1.add(radioNom);
        radioGroup1.add(radioID);
        radioNom.setSelected(true);
        radioGroup2.add(radioIn);
        radioGroup2.add(radioCom);
        radioGroup2.add(radioTodos);
        radioTodos.setSelected(true);
    }
           
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioGroup1 = new javax.swing.ButtonGroup();
        radioGroup2 = new javax.swing.ButtonGroup();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaArchivo = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        radioNom = new javax.swing.JRadioButton();
        radioID = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        radioCom = new javax.swing.JRadioButton();
        radioIn = new javax.swing.JRadioButton();
        radioTodos = new javax.swing.JRadioButton();

        setClosable(true);

        tablaArchivo.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tablaArchivo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tablaArchivo);

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        radioNom.setText("Nombre");

        radioID.setText("No. Empleado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioID)
                    .addComponent(radioNom))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(radioNom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioID)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        radioCom.setText("Completos");

        radioIn.setText("Incompletos");

        radioTodos.setText("Todos");
        radioTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioCom)
                    .addComponent(radioIn)
                    .addComponent(radioTodos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(radioTodos)
                .addGap(18, 18, 18)
                .addComponent(radioCom)
                .addGap(18, 18, 18)
                .addComponent(radioIn)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(263, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioTodosActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
       limpiar(tablaArchivo);
        txtBuscar.setText(txtBuscar.getText().toUpperCase());
        String parametro="";
        int tipo=0;
        if(radioID.isSelected()){ parametro="e.id_empleado";}
        if(radioNom.isSelected()){ parametro="e.nombre";}
        if(radioTodos.isSelected()){ tipo=1;}
        if(radioCom.isSelected()){ tipo=2;}
        if(radioIn.isSelected()){ tipo=3;}
        doc.busqueda(modeloDoc,txtBuscar.getText(), parametro,tipo);        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton radioCom;
    private javax.swing.ButtonGroup radioGroup1;
    private javax.swing.ButtonGroup radioGroup2;
    private javax.swing.JRadioButton radioID;
    private javax.swing.JRadioButton radioIn;
    private javax.swing.JRadioButton radioNom;
    private javax.swing.JRadioButton radioTodos;
    private javax.swing.JTable tablaArchivo;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
