
import BD.Empleados;
import java.awt.Font;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author edgar
 */
public class VistaEmpleados extends javax.swing.JInternalFrame {
DefaultTableModel modeloEmpleado;
Empleados empleados;
JDesktopPane esc;
    /**
     * Creates new form VistaEmpleados
     */
    public VistaEmpleados(JDesktopPane escritorio) {
        initComponents();
        esc=escritorio;
        empleados=new Empleados();
        tablanew2();
        modeloEmpleado = (DefaultTableModel) tablaEmpleado.getModel();
        TablaDimensiones();
        TotalEmpleados();
        RadioGroup();
        
    }
    private void RadioGroup(){
       radioGroup1.add(radioNom1);
        radioGroup1.add(radioID1);
        radioGroup1.add(radioDepart1);
        radioNom1.setSelected(true);
        radioGroup2.add(radioTodos);
        radioGroup2.add(radioActivos);
        radioGroup2.add(radioInactivos);
        radioActivos.setSelected(true);
    }
    private void TablaDimensiones(){
    
      tablaEmpleado.setRowHeight(60);
      tablaEmpleado.getTableHeader().setFont(new Font("Ubuntu", 1,15));
      tablaEmpleado.getColumnModel().getColumn(6).setPreferredWidth(2);
      tablaEmpleado.getColumnModel().getColumn(0).setPreferredWidth(40);
      tablaEmpleado.getColumnModel().getColumn(1).setPreferredWidth(10);
      tablaEmpleado.getColumnModel().getColumn(2).setPreferredWidth(250);
       tablaEmpleado.getColumnModel().getColumn(4).setPreferredWidth(50);
      /*
      tablaProductos.getTableHeader().setFont(new Font("Ubuntu", 1,15));*/
    }
    private void limpiar(JTable tabla) {
        while (tabla.getRowCount() > 0) {
            ((DefaultTableModel) tabla.getModel()).removeRow(0);
        }
    }
    private void tablanew2(){
          DefaultTableModel modelo3=new DefaultTableModel(){
        public Class getColumnClass(int indiceColumna){
        Object stefany=getValueAt(0, indiceColumna);
        if(stefany == null){
            return Object.class;
        }else{
        return stefany.getClass();
        }
       }
        };
         
        modelo3.addColumn("No. Empleado",new Object[] {});
        modelo3.addColumn("Imagen",new Object[] {});
        modelo3.addColumn("Nombre",new Object[] {});
        modelo3.addColumn("Departamentos",new Object[] {});
        modelo3.addColumn("Area.",new Object[] {});
        modelo3.addColumn("Puesto",new Object[] {});
        modelo3.addColumn("Status",new Object[] {});
       
       
        this.tablaEmpleado.setModel(modelo3);
      
      }
 private void TotalEmpleados(){
        limpiar(tablaEmpleado);
      // modeloEmpleado = (DefaultTableModel) tablaEmpleado.getModel();
        empleados.ReadEmpleado(modeloEmpleado);
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioGroup1 = new javax.swing.ButtonGroup();
        radioGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        radioID1 = new javax.swing.JRadioButton();
        radioNom1 = new javax.swing.JRadioButton();
        radioDepart1 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpleado = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        radioActivos = new javax.swing.JRadioButton();
        radioInactivos = new javax.swing.JRadioButton();
        radioTodos = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setClosable(true);

        radioID1.setText("No. Empleado");

        radioNom1.setText("Nombre");

        radioDepart1.setText("Departamento");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioDepart1)
                    .addComponent(radioNom1)
                    .addComponent(radioID1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioID1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioNom1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioDepart1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        tablaEmpleado.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tablaEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaEmpleado);

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        radioActivos.setText("Activos");

        radioInactivos.setText("Inactivos");

        radioTodos.setText("Todos");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioActivos)
                    .addComponent(radioInactivos)
                    .addComponent(radioTodos))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioActivos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioInactivos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radioTodos)
                .addContainerGap())
        );

        jButton1.setText("Ver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(25, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(37, 37, 37)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
      limpiar(tablaEmpleado);
        txtBuscar.setText(txtBuscar.getText().toUpperCase());
        String parametro="";
        int tipo=0;
        if(radioID1.isSelected()){ parametro="e.id_empleado";}
        if(radioNom1.isSelected()){ parametro="e.nombre";}
        if(radioDepart1.isSelected()){ parametro="d.departamento";}
        if(radioTodos.isSelected()){ tipo=1;}
        if(radioActivos.isSelected()){ tipo=2;}
        if(radioInactivos.isSelected()){ tipo=3;}
        empleados.busqueda(modeloEmpleado,txtBuscar.getText(), parametro,tipo);
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         esc.removeAll();
        esc.repaint();
        AddEmpleado v2=new AddEmpleado("1",1);
           esc.add(v2);
        try {
           v2.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        v2.show();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioActivos;
    private javax.swing.JRadioButton radioDepart1;
    private javax.swing.ButtonGroup radioGroup1;
    private javax.swing.ButtonGroup radioGroup2;
    private javax.swing.JRadioButton radioID1;
    private javax.swing.JRadioButton radioInactivos;
    private javax.swing.JRadioButton radioNom1;
    private javax.swing.JRadioButton radioTodos;
    private javax.swing.JTable tablaEmpleado;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
